-- SCRIPT DE REPARACIÓN DE TABLA PRESUPUESTOS (v1.1.2) --
-- ADVERTENCIA: Este script borrará los presupuestos existentes para crear la nueva estructura.

-- 1. Eliminar la tabla antigua para limpiar el cache
DROP TABLE IF EXISTS public.presupuestos CASCADE;

-- 2. Crear la tabla con la estructura exacta que pide la App
CREATE TABLE public.presupuestos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number SERIAL, -- Genera 1, 2, 3...
  client_id UUID REFERENCES public.clientes(id) ON DELETE SET NULL,
  date_created DATE DEFAULT CURRENT_DATE,
  validity_days INTEGER DEFAULT 15,
  short_description TEXT NOT NULL,
  long_description TEXT,
  estimated_value DECIMAL DEFAULT 0,
  status TEXT DEFAULT 'PENDIENTE',
  images TEXT[] DEFAULT '{}',
  materials JSONB DEFAULT '[]', -- Lista de materiales [{id, description, quantity}]
  tools TEXT[] DEFAULT '{}',     -- IDs de herramientas
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Habilitar Seguridad (RLS)
ALTER TABLE public.presupuestos ENABLE ROW LEVEL SECURITY;

-- 4. Crear política de acceso total para usuarios autenticados
CREATE POLICY "Gestion total presupuestos" ON public.presupuestos 
FOR ALL USING (true) WITH CHECK (true);

-- 5. RECOMENDACIÓN: Ejecutar esto y luego refrescar la App en el navegador.
