-- SCRIPT DE BASE DE DATOS PARA PRESUPUESTOS (v1.1.0) --

-- 1. TABLA DE PRESUPUESTOS
CREATE TABLE IF NOT EXISTS public.presupuestos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number SERIAL, -- Numero de orden auto-incremental (000001, 000002...)
  client_id UUID REFERENCES public.clientes(id) ON DELETE SET NULL,
  date_created DATE DEFAULT CURRENT_DATE,
  validity_days INTEGER DEFAULT 15,
  short_description TEXT NOT NULL,
  long_description TEXT,
  estimated_value DECIMAL DEFAULT 0,
  status TEXT DEFAULT 'PENDIENTE', -- PENDIENTE, ENVIADO, APROBADO, RECHAZADO
  images TEXT[] DEFAULT '{}', -- Array de URLs de imagenes
  materials JSONB DEFAULT '[]', -- Lista de materiales [{id, description, quantity}]
  tools TEXT[] DEFAULT '{}', -- Array de IDs de herramientas sugeridas
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. HABILITAR SEGURIDAD (RLS)
ALTER TABLE public.presupuestos ENABLE ROW LEVEL SECURITY;

-- 3. POLITICAS DE ACCESO
DROP POLICY IF EXISTS "Gestion total presupuestos" ON public.presupuestos;
CREATE POLICY "Gestion total presupuestos" ON public.presupuestos 
FOR ALL USING (true) WITH CHECK (true);

-- 4. POLITICAS PARA EL STORAGE (BUCKET: presupuestos)
-- Recuerda crear el bucket 'presupuestos' manualmente en Supabase Storage primero.
DROP POLICY IF EXISTS "Subida presupuestos" ON storage.objects;
CREATE POLICY "Subida presupuestos" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'presupuestos' AND auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Ver presupuestos" ON storage.objects;
CREATE POLICY "Ver presupuestos" ON storage.objects FOR SELECT USING (bucket_id = 'presupuestos');

DROP POLICY IF EXISTS "Borrar presupuestos" ON storage.objects;
CREATE POLICY "Borrar presupuestos" ON storage.objects FOR DELETE USING (bucket_id = 'presupuestos' AND auth.role() = 'authenticated');
